//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gu.Localization.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gu.Localization.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So neutral.
        /// </summary>
        internal static string AllLanguages {
            get {
                return ResourceManager.GetString("AllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnglishOnly {
            get {
                return ResourceManager.GetString("EnglishOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first: {0}, second:{1}.
        /// </summary>
        internal static string first___0___second__1_ {
            get {
                return ResourceManager.GetString("first___0___second__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: {0}.
        /// </summary>
        internal static string InvalidFormat__0__ {
            get {
                return ResourceManager.GetString("InvalidFormat__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So neutral.
        /// </summary>
        internal static string NeutralOnly {
            get {
                return ResourceManager.GetString("NeutralOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoTranslation {
            get {
                return ResourceManager.GetString("NoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral: {0}.
        /// </summary>
        internal static string ValidFormat__0__ {
            get {
                return ResourceManager.GetString("ValidFormat__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral first: {0}, second {1:F2}.
        /// </summary>
        internal static string ValidFormat__0__1__ {
            get {
                return ResourceManager.GetString("ValidFormat__0__1__", resourceCulture);
            }
        }
    }
}
