namespace Gu.Localization.Analyzers.Tests.GULOC01KeyExistsAnalyzerTests
{
    using Gu.Roslyn.Asserts;
    using NUnit.Framework;

    public static class Diagnostics
    {
        private static readonly InvocationAnalyzer Analyzer = new();
        private static readonly ExpectedDiagnostic ExpectedDiagnostic = ExpectedDiagnostic.Create(Descriptors.GULOC01KeyExists);

        private const string ResourcesCode = @"
namespace RoslynSandbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""15.0.0.0"")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(""Microsoft.Performance"", ""CA1811:AvoidUncalledPrivateCode"")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""RoslynSandbox.Properties.Resources"", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString(""Key"", resourceCulture);
            }
        }
    }
}";

        private const string TranslateCode = @"
namespace RoslynSandbox.Properties
{
    using Gu.Localization;

    public static class Translate
    {
        /// <summary>Call like this: Translate.Key(nameof(Resources.Saved_file__0_)).</summary>
        /// <param name=""key"">A key in Properties.Resources</param>
        /// <param name=""errorHandling"">How to handle translation errors like missing key or culture.</param>
        /// <returns>A translation for the key.</returns>
        public static string Key(string key, ErrorHandling errorHandling = ErrorHandling.ReturnErrorInfoPreserveNeutral)
        {
            return TranslationFor(key, errorHandling).Translated;
        }

        /// <summary>Call like this: Translate.Key(nameof(Resources.Saved_file__0_)).</summary>
        /// <param name=""key"">A key in Properties.Resources</param>
        /// <param name=""errorHandling"">How to handle translation errors like missing key or culture.</param>
        /// <returns>A translation for the key.</returns>
        public static ITranslation TranslationFor(string key, ErrorHandling errorHandling = ErrorHandling.ReturnErrorInfoPreserveNeutral)
        {
            return Gu.Localization.Translation.GetOrCreate(Resources.ResourceManager, key, errorHandling);
        }
    }
}";

        [Test]
        public static void TranslatorTranslateStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translator.Translate(Resources.ResourceManager, ↓""Missing"");
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslatorTranslateStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translate = Translator.Translate(Properties.Resources.ResourceManager, ↓""Missing"");
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslatorTranslateNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translator.Translate(Resources.ResourceManager, ↓nameof(Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslatorTranslateMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translator.Translate(Resources.ResourceManager, ↓Resources.Key);
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslatorTranslateNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translate = Translator.Translate(Properties.Resources.ResourceManager, ↓nameof(Properties.Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslateTranslationForStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translate.TranslationFor(↓""Missing"");
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateTranslationForStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translate = Properties.Translate.TranslationFor(↓""Missing"");
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateTranslationForNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translate.TranslationFor(↓nameof(Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateTranslationForMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Properties.Translate.TranslationFor(↓Resources.Key);
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateTranslationForNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translate = Properties.Translate.TranslationFor(↓nameof(C));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateKeyStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translate.Key(↓""Missing"");
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateKeyStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translate = Properties.Translate.Key(↓""Missing"");
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateKeyNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Translate.Key(↓nameof(Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateKeyMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Properties.Translate.Key(↓Resources.Key);
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslateKeyNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translate = Properties.Translate.Key(↓nameof(C));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void TranslationGetOrCreateStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translation = Translation.GetOrCreate(Resources.ResourceManager, ↓""Missing"");
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslationGetOrCreateStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translation = Translation.GetOrCreate(Properties.Resources.ResourceManager, ↓""Missing"");
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslationGetOrCreateNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translation = Translation.GetOrCreate(Resources.ResourceManager, ↓nameof(Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslationGetOrCreateMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translation = Translation.GetOrCreate(Resources.ResourceManager, ↓Resources.Key);
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void TranslationGetOrCreateNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    using Gu.Localization;

    public class C
    {
        public C()
        {
            var translation = Translation.GetOrCreate(Properties.Resources.ResourceManager, ↓nameof(C));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetObject(↓""Missing"");
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetObject(↓""Missing"");
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetObject(↓nameof(Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetObject(↓Resources.Key);
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetObject(↓nameof(C));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectWithCultureStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetObject(↓""Missing"", System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectWithCultureStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetObject(↓""Missing"", System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectWithCultureNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetObject(↓nameof(Resources), System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectWithCultureMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetObject(↓Resources.Key, System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetObjectWithCultureNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetObject(↓nameof(C), System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetString(↓""Missing"");
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓""Missing"");
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetString(↓nameof(Resources));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓Resources.Key);
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓nameof(C));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringWithCultureStringLiteralWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetString(↓""Missing"", System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";

            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringWithCultureStringLiteralFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓""Missing"", System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringWithCultureNameofPropertyWithUsing()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Resources.ResourceManager.GetString(↓nameof(Resources), System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringWithCultureMissingNameof()
        {
            var code = @"
namespace RoslynSandbox
{
    using RoslynSandbox.Properties;

    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓Resources.Key, System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, TranslateCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringWithCultureNameofPropertyFullyQualified()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C()
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓nameof(C), System.Globalization.CultureInfo.GetCultureInfo(""sv-SE""));
        }
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }

        [Test]
        public static void ResourceManagerGetStringWithEnumToString()
        {
            var code = @"
namespace RoslynSandbox
{
    public class C
    {
        public C(SomeEnum someEnum)
        {
            var translate = Properties.Resources.ResourceManager.GetString(↓someEnum.ToString());
        }
    }

    public enum SomeEnum
    {
        Key,
        Missing,
    }
}";
            RoslynAssert.Diagnostics(Analyzer, ExpectedDiagnostic, ResourcesCode, code);
        }
    }
}
